export interface BlogPost {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  date: string;
  author: string;
  category: string;
  readTime: string;
}

export const blogPosts: BlogPost[] = [
  {
    title: "The Shift to Autonomous SaaS",
    slug: "shift-to-autonomous-saas",
    excerpt: "Why AI-powered systems that make decisions are the future of SaaS.",
    date: "2026-02-15",
    author: "Maysan Engineering Team",
    category: "Architecture",
    readTime: "4 min",
    content: "# Autonomous SaaS\n\nAI that makes decisions, not just automation that follows rules.",
  },
  {
    title: "Infrastructure as Code",
    slug: "iac-scaling-enterprise",
    excerpt: "How IaC helps enterprises deploy faster and safer.",
    date: "2026-02-10",
    author: "Sanjay Mandal",
    category: "Infrastructure",
    readTime: "5 min",
    content: "# Infrastructure as Code\n\nDeploy in minutes what used to take weeks.",
  },
  {
    title: "The Death of Monoliths",
    slug: "death-of-monoliths",
    excerpt: "Why modular architecture beats old-school code.",
    date: "2026-02-05",
    author: "Maysan Architecture",
    category: "Methodology",
    readTime: "3 min",
    content: "# Modular Architecture\n\nUpdate one part without breaking the whole system.",
  },
  {
    title: "AI Integration That Works",
    slug: "ai-integration-growth-lever",
    excerpt: "From AI hype to real ROI in your product.",
    date: "2026-01-28",
    author: "Maysan Engineering",
    category: "AI & ML",
    readTime: "4 min",
    content: "# Real AI\n\nAI that drives revenue, not just looks smart.",
  },
  {
    title: "Security by Design",
    slug: "security-by-design",
    excerpt: "Security built in from day one, not added later.",
    date: "2026-01-20",
    author: "Security Operations",
    category: "Security",
    readTime: "5 min",
    content: "# Zero-Trust Security\n\nNever trust, always verify.",
  },
  {
    title: "Edge Computing for Speed",
    slug: "saas-edge-computing",
    excerpt: "Why milliseconds matter in global products.",
    date: "2026-01-12",
    author: "Infrastructure Team",
    category: "Performance",
    readTime: "3 min",
    content: "# Edge Computing\n\nData processed closer to users means faster responses.",
  },
  {
    title: "The Rise of Vertical SaaS",
    slug: "rise-of-vertical-saas",
    excerpt: "Specialized tools beat generic solutions.",
    date: "2025-12-28",
    author: "Maysan Insights",
    category: "Business",
    readTime: "4 min",
    content: "# Vertical SaaS\n\nDeep industry focus wins over broad solutions.",
  },
  {
    title: "Real-time Data Pipelines",
    slug: "realtime-data-pipelines",
    excerpt: "Moving from batch to real-time insights.",
    date: "2025-12-15",
    author: "Data Engineering",
    category: "Architecture",
    readTime: "5 min",
    content: "# Real-time Data\n\nInstant insights from instant data flow.",
  },
  {
    title: "UX for Enterprise",
    slug: "ux-psychology-enterprise",
    excerpt: "Complex tools can be simple to use.",
    date: "2025-12-02",
    author: "Design Team",
    category: "Design",
    readTime: "3 min",
    content: "# Enterprise UX\n\nPowerful software doesn't have to be complicated.",
  },
  {
    title: "Composable SaaS",
    slug: "composable-saas-future",
    excerpt: "Build like LEGO blocks for maximum flexibility.",
    date: "2025-11-18",
    author: "Maysan Architecture",
    category: "Architecture",
    readTime: "4 min",
    content: "# Composable Architecture\n\nSwap parts without rebuilding everything.",
  },
  {
    title: "API-First Development",
    slug: "api-first-development",
    excerpt: "Build the API first, everything else follows.",
    date: "2025-11-05",
    author: "Engineering Team",
    category: "Methodology",
    readTime: "4 min",
    content: "# API-First\n\nThe API is the product. Everything else is a consumer.",
  },
  {
    title: "Tech for Traditional Business",
    slug: "tech-empowering-traditional-enterprises",
    excerpt: "How modern tech lifts legacy businesses.",
    date: "2026-03-05",
    author: "Maysan Strategic Team",
    category: "Transformation",
    readTime: "5 min",
    content: "# Digital Transformation\n\nOld businesses, new tech capabilities.",
  },
  {
    title: "Enterprise Tools for Everyone",
    slug: "democratizing-enterprise-stack",
    excerpt: "Big tech tools now accessible to smaller companies.",
    date: "2026-03-01",
    author: "Sanjay Mandal",
    category: "Insights",
    readTime: "4 min",
    content: "# Democratized Tech\n\nFortune 500 tools now for every business.",
  },
  {
    title: "SME Digital Revolution",
    slug: "sme-digital-revolution",
    excerpt: "SMEs can now compete with big players.",
    date: "2026-02-28",
    author: "Maysan Engineering",
    category: "Business",
    readTime: "5 min",
    content: "# SME Advantage\n\nTech gaps are closing. Opportunities are opening.",
  },
  {
    title: "Custom Software ROI",
    slug: "custom-software-sme-growth",
    excerpt: "Why custom beats generic every time.",
    date: "2026-02-25",
    author: "Growth Strategy",
    category: "Optimization",
    readTime: "3 min",
    content: "# Custom ROI\n\nSoftware built for you beats software built for everyone.",
  },
  {
    title: "AI for Legacy Business",
    slug: "ai-transformation-legacy",
    excerpt: "From spreadsheets to AI-powered operations.",
    date: "2026-02-22",
    author: "AI Implementation Team",
    category: "AI & ML",
    readTime: "5 min",
    content: "# AI Transformation\n\nTurn old data into smart predictions.",
  },
  {
    title: "Enterprise-Grade for All",
    slug: "maysan-labs-sme-scale",
    excerpt: "Big company tech for growing businesses.",
    date: "2026-02-20",
    author: "Maysan Engineering",
    category: "Methodology",
    readTime: "4 min",
    content: "# Scale Up\n\nEnterprise patterns. Startup speed. Your budget.",
  },
  {
    title: "Digital Migration Guide",
    slug: "digital-migration-strategies",
    excerpt: "Practical steps from paper to digital.",
    date: "2026-02-18",
    author: "Tech Consulting",
    category: "Transformation",
    readTime: "5 min",
    content: "# Migration Path\n\nStep by step from manual to digital.",
  },
  {
    title: "Accessible Infrastructure",
    slug: "accessible-enterprise-infrastructure",
    excerpt: "Serverless and edge are now for everyone.",
    date: "2026-02-14",
    author: "Infrastructure Team",
    category: "Performance",
    readTime: "5 min",
    content: "# Cloud Access\n\nPowerful infrastructure no longer needs deep pockets.",
  },
  {
    title: "Custom vs Off-the-Shelf",
    slug: "custom-vs-off-the-shelf",
    excerpt: "The long-term math on build vs buy.",
    date: "2026-02-12",
    author: "Business Strategy",
    category: "Business",
    readTime: "4 min",
    content: "# Build vs Buy\n\nCustom pays off. Generic hits walls.",
  },
  {
    title: "Autonomous Future",
    slug: "future-is-autonomous",
    excerpt: "Software that runs itself is coming.",
    date: "2026-02-08",
    author: "Maysan Architecture",
    category: "Architecture",
    readTime: "5 min",
    content: "# Autonomous Operations\n\nSoftware handles the how. Humans own the why.",
  },
];