import pptxgen from "pptxgenjs";

export interface PresentationCell {
  text: string;
  bold?: boolean;
  textColor?: string;
  bgColor?: string;
}

export interface TableData {
  headers: string[];
  widths: number[];
  rows: PresentationCell[][];
}

export interface CalloutBox {
  text: string;
  type: "success" | "neutral";
}

export interface SlideData {
  slideNumber: number;
  title: string;
  subtitle: string;
  layoutType: "table" | "grid_cards" | "comparison";
  tableData?: TableData;
  calloutBox?: CalloutBox;
}

export interface PresentationJSON {
  slides: SlideData[];
}

export async function compileMaysanPresentation(
  jsonData: PresentationJSON
): Promise<Blob> {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_16x9";
  pptx.author = "Maysan Labs";
  pptx.company = "Maysan Labs";
  pptx.subject = "Generated by Maysan Labs Presentation Engine";
  pptx.title = "Maysan Labs Presentation";

  const totalSlides = jsonData.slides.length;

  for (const slideData of jsonData.slides) {
    const slide = pptx.addSlide();

    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: "100%",
      h: 1.1,
      fill: { color: "162447" },
    });

    slide.addText(slideData.title, {
      x: 0.5,
      y: 0.15,
      w: 10,
      h: 0.4,
      fontSize: 20,
      bold: true,
      color: "FFFFFF",
      fontFace: "Arial",
    });

    slide.addText(slideData.subtitle, {
      x: 0.5,
      y: 0.6,
      w: 10,
      h: 0.3,
      fontSize: 10,
      color: "A5D8DD",
      fontFace: "Arial",
    });

    slide.addText(
      `PAGE ${slideData.slideNumber} / ${totalSlides}`,
      {
        x: 11.5,
        y: 0.35,
        w: 1.3,
        h: 0.4,
        fontSize: 9,
        bold: true,
        color: "FFFFFF",
        fill: { color: "1F6B75" },
        align: "center",
        rectRadius: 0.1,
      }
    );

    if (slideData.layoutType === "table" && slideData.tableData) {
      const headerRow = slideData.tableData.headers.map((h) => ({
        text: h,
        options: {
          fill: { color: "162447" },
          color: "FFFFFF",
          bold: true,
          fontSize: 9,
          fontFace: "Arial",
        },
      }));

      const dataRows = slideData.tableData.rows.map((row) =>
        row.map((cell) => ({
          text: cell.text,
          options: {
            fill: cell.bgColor
              ? { color: cell.bgColor }
              : { color: "FFFFFF" },
            color: cell.textColor || "1F2937",
            bold: cell.bold || false,
            fontSize: 8.5,
            fontFace: "Arial",
          },
        }))
      );

      const compiledRows = [headerRow, ...dataRows];

      slide.addTable(compiledRows, {
        x: 0.5,
        y: 1.8,
        w: 12.333,
        colW: slideData.tableData.widths,
        border: { type: "solid", color: "D1D5DB", pt: 0.5 },
        fontSize: 8.5,
        fontFace: "Arial",
        rowH: 0.45,
      });
    }

    if (slideData.calloutBox) {
      const calloutColor =
        slideData.calloutBox.type === "success"
          ? { text: "065F46", fill: "ECFDF5", line: "34D399" }
          : { text: "92400E", fill: "FFFBEB", line: "F59E0B" };

      slide.addShape(pptx.ShapeType.rect, {
        x: 0.5,
        y: 5.9,
        w: 12.333,
        h: 0.8,
        fill: { color: calloutColor.fill },
        line: { color: calloutColor.line, width: 1 },
      });

      slide.addText(slideData.calloutBox.text, {
        x: 0.6,
        y: 5.9,
        w: 12.133,
        h: 0.8,
        fontSize: 9.5,
        color: calloutColor.text,
        fontFace: "Arial",
        valign: "middle",
        inset: 10,
      });
    }

    slide.addShape(pptx.ShapeType.rect, {
      x: 0.5,
      y: 7.0,
      w: 12.333,
      h: 0.02,
      fill: { color: "D1D5DB" },
    });

    slide.addText(
      `EduMaysan  ·  Maysan Labs      |      business@maysanlabs.com      |      Page ${slideData.slideNumber} of ${totalSlides}`,
      {
        x: 0.5,
        y: 7.05,
        w: 12.333,
        h: 0.3,
        fontSize: 8.5,
        color: "6B7280",
        align: "center",
        fontFace: "Arial",
      }
    );
  }

  const blob = (await pptx.write({ outputType: "blob" })) as Blob;
  return blob;
}
